name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/portfolio:latest
          build-args: |
            VITE_LINKEDIN=${{ vars.VITE_LINKEDIN }}
            VITE_ASPX=${{ vars.VITE_ASPX }}
            VITE_VUE=${{ vars.VITE_VUE }}
            VITE_REACT=${{ vars.VITE_REACT }}
            VITE_BACKEND=${{ vars.VITE_BACKEND }}
            VITE_AWS=${{ vars.VITE_AWS }}
            VITE_GITHUB=${{ vars.VITE_GITHUB }}

      - name: Execute Render Deploy
        run: curl ${{ secrets.RENDER_API }}
        
